### ISSUE TITLE
[!tmp.empty()] unknown format type [chasen]

### ISSUE THREAD

**Issue by nikoharo** [ytyt-yt/anki-biaori#2]
好像是没有指定chasen的格式？我不知道如何操作
![Screen Shot 2022-06-14 at 12 42 03](https://user-images.githubusercontent.com/96216203/173488744-960bd366-088d-407d-9e5e-e972ba090ee5.png)

**Comment by nikoharo** [comment]
貌似与furigana最新版有关，那边有人说安装0.996.5版本，但我无法安装，请问还有其他的解决办法吗

**Comment by ytyt-yt** [comment]
我没有遇到这个问题 猜测是你 MeCab 没装好（没装字典 `mecab-ipadic`？）

我不是用的macOS，你可以试试 homebrew 安装 `mecab` 和 `mecab-ipadic`
